version: "3.9"

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./www/assets:/www/assets
    ports:
      - 8081:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
