version: "3.9"

services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    restart: unless-stopped
    volumes:
      - ./www/assets:/www/assets
    networks:
      - caddy_caddynet
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
      - PORT=8080

networks:
  caddy_caddynet:
    external: true
